const archivos = [


"4 Non Blondes - Whats Up.mp3",
"AbbA - The Winner Takes It All.mp3",
"Ace of Base  - All That She Wants.mp3",
"Ace of Base - Beautiful Life.mp3",
"Ace of base - Dont Turn Around.mp3",
"Ace of Base - Happy Nation.mp3",
"Alien Ant Farm  - Smooth Criminal.mp3",
"Andry Logan  - I Could Love You More.mp3",
"Annie lennox - A Whiter Shade of Pale.mp3",
"ATeens  - Super Trouper.mp3",
"Beck - Loser.mp3",
"Bee Gees - Alone.mp3",
"Belinda Carlisle  - Heaven Is a Place on Earth.mp3",
"Berlin  - Take My Breath Away.mp3",
"Billy Idol  - Eyes Without A Face.mp3",
"Black  - Wonderful Life.mp3",
"Blind Melon  - No Rain.mp3",
"blink-182  - All The Small Things.mp3",
"Bloodhound Gang  - The Bad Touch.mp3",
"Blur  - Song 2.mp3",
"Bon Jovi  - Always.mp3",
"Bonnie Tyler  - It's a Heartache.mp3",
"Bonnie Tyler  - Total Eclipse of the Heart.mp3",
"Bruce Springsteen - Dancing In the Dark.mp3",
"Bryan Ferry  - Slave To Love.mp3",
"Carly Simon  - Coming Around Again.mp3",
"Celine Dion  - My Heart Will Go On.mp3",
"Chicago  - Hard to Say I'm Sorry.mp3",
"Chris de Burgh  - The Lady In Red.mp3",
"Christopher Cross  - Arthur's Theme (Best That You Can Do).mp3",
"Counting Crows  - Mr. Jones.mp3",
"Crowded House  - Don't Dream It's Over.mp3",
"Cyndi Lauper  - All Through the Night.mp3",
"Debbie Gibson  - Lost In Your Eyes.mp3",
"Dominic Miller  - Shape Of My Heart.mp3",
"Duran Duran  - Ordinary World.mp3",
"Elton John  - Sacrifice.mp3",
"Enigma  - Return To Innocence.mp3",
"Enrique Iglesias  - Hero.mp3",
"Europe - The Final Countdown.mp3",
"F.R. David  - Words.mp3",
"Fastball  - The Way.mp3",
"Garbage  - Push It.mp3",
"Garbage  - Stupid Girl.mp3",
"Gazebo  - I Like Chopin.mp3",
"George Michael  - Careless Whisper.mp3",
"Green Day  - Basket Case.mp3",
"Green Day  - When I Come Around.mp3",
"Guns N' Roses  - Don't Cry.mp3",
"Guns N' Roses  - November Rain.mp3",
"Gwen Stefani  - Cool.mp3",
"Hanson  - MMMBop.mp3",
"Heart  - Alone.mp3",
"Iggy Pop  - The Passenger.mp3",
"INXS  - Never Tear Us Apart.mp3",
"Irene Cara  - Flashdance... What a Feeling.mp3",
"Irene Cara  - What A Feeling.mp3",
"Jennifer Rush  - Come Give Me Your Hand.mp3",
"Jennifer Rush  - If You're Ever Gonna Lose My Love.mp3",
"Jennifer Rush  - Stronghold.mp3",
"Jennifer Rush  - The Power of Love.mp3",
"Lady Gaga  - Bad Romance.mp3",
"Lenny Kravitz  - Are You Gonna Go My Way.mp3",
"Linkin Park  - Numb.mp3",
"Lionel Richie  - Say You, Say Me.mp3",
"Madonna  - Frozen.mp3",
"Madonna  - Live to Tell.mp3",
"Martika  - Toy Soldiers.mp3",
"Men at Work  - Down Under.mp3",
"Metallica  - Enter Sandman.mp3",
"Metallica  - Nothing Else Matters.mp3",
"Mr. Mister  - Broken Wings.mp3",
"Nelly Furtado  - I'm Like A Bird.mp3",
"Nelly Furtado  - Turn Off The Light.mp3",
"Nightwish - Nemo.mp3",
"Nirvana  - The Man Who Sold The World.mp3",
"No Doubt - Don't Speak.mp3",
"Oasis - Dont look back in anger.mp3",
"Patrick Swayze  - She's Like the Wind.mp3",
"Paul Young  - Every Time You Go Away.mp3",
"Pet Shop Boys  - Go West.mp3",
"Pet Shop Boys  - It's a Sin.mp3",
"Phil Collins  - Another Day in Paradise.mp3",
"Pure - The Lightning Seeds .mp3",
"Queen - Radio Ga Ga.mp3",
"R.E.M.  - Everybody Hurts.mp3",
"R.E.M.  - Losing My Religion.mp3",
"Radiohead  - Creep.mp3",
"Red Hot Chili Peppers  - Californication.mp3",
"REO Speedwagon  - Can't Fight This Feeling.mp3",
"Republica  - Drop Dead Gorgeous.mp3",
"Richard Marx  - Hazard.mp3",
"Robbie Williams - Supreme.mp3",
"Robin Gibb  - Like a Fool.mp3",
"Roxette  - Listen To Your Heart.mp3",
"Roxette  - The Look.mp3",
"Roy Orbison  - You Got It.mp3",
"Savage Garden  - I Want You.mp3",
"Soul Asylum - Runaway Train.mp3",
"Starship  - Nothing's Gonna Stop Us Now.mp3",
"Survivor  - Burning Heart .mp3",
"Ten Sharp  - You.mp3",
"The Bangles  - Eternal Flame.mp3",
"The Cardigans  - Lovefool.mp3",
"The Cranberries  - Dreams.mp3",
"The Cranberries  - Zombie.mp3",
"The Cure  - Friday I'm In Love.mp3",
"The Offspring  - The Kids Aren't Alright.mp3",
"The Rasmus  - In the Shadows.mp3",
"The Rolling Stones  - Paint It, Black.mp3",
"The Smashing Pumpkins  - 1979.mp3",
"The Verve  - Bitter Sweet Symphony.mp3",
"The Wallflowers  - One Headlight.mp3",
"Toni Braxton  - Un-Break My Heart.mp3",
"TOTO  - Africa.mp3",
"Tracy Chapman  - Baby Can I Hold You.mp3",
"U2  - Mysterious Ways.mp3",
"Vanilla Ice  - Ice Ice Baby.mp3",
"White Town  - Your Woman.mp3",
"Whitney Houston  - I Will Always Love You.mp3"

];
